### ISSUE TITLE
Prosemirror Syntax error after enabling and disabling CKGEdit

### ISSUE THREAD

**Issue by jorbig** [cosmocode/dokuwiki-plugin-prosemirror#102]
Prosemirror is great, but when coming from the popular CKGEdit it shows an error message to all users who have used the CKGEditor before, until they remove the cookies for the website.

There was an error in the WYSIWYG editor. You will be redirected to the syntax editor in 5 seconds. vervolgens na 5 secondens: Parsing the data generated by Prosemirror failed with message: "Error decoding prosemirror json Syntax error"

This happens only with Prosemirror whenever I switch to it from CKGEdit.
What could be causing this bug? And more important: how to fix it?

**Comment by annda** [comment]
As the documentation page says, CKGEdit conflicts with Prosemirror so you need to choose one of the two.

The reason is that CKGEdit modifies the underlying syntax for its own purposes and sometimes the modified version cannot be parsed by Prosemirror.
