### ISSUE TITLE
Bug: saving a page fails when lists have multiline items

### ISSUE THREAD

**Issue by jorbig** [cosmocode/dokuwiki-plugin-prosemirror#103]
When a page has a list with one or more multiline items, changes to the page can't be saved anymore by Prosemirror, since it will return an error message: 'Invalid node type received: text' and 'Failed to handle action: save'.

To reproduce this error: it happens when a list has an item with a linebreak \\ (as explained here: https://www.dokuwiki.org/faq:lists#multiline_list_items). The default DokuWiki editor handles this fine, but Prosemirror doesn't.

**Comment by Krit1960** [comment]
I do get this error during saving from the WYSIWYG editor when I include following syntax:

text \\ **bold text**

**Comment by jorbig** [comment]
This issue is fixed on multiline lists. Thank you very much, @splitbrain!

The bug mentioned by @Krit1960 still remains though:

> I do get this error during saving from the WYSIWYG editor when I include following syntax:
> 
> `text \\ **bold text**`

The error shown in that situation is:
`FIXME: better message for general error! Invalid node type received: text`
and:
` Failed to handle action: save`

**Comment by annda** [comment]
@jorbig Check the latest relaease
