### ISSUE TITLE
is there any problem for processing UTF-8 charaters?

### ISSUE THREAD

**Issue by dryoo** [cosmocode/dokuwiki-plugin-prosemirror#128]
Thank you for your great plugin. I like it.

I tried to add Korean translation but, 
Browser says there is an error.

> DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the **Latin1** range.

https://github.com/dryoo/dokuwiki-plugin-prosemirror/tree/master/lang/ko

Is this problem of my translation or plugin's ?

**Comment by splitbrain** [comment]
That is weird. UTF-8 should be fine. We'll have to check if we can reproduce the problem.

**Comment by annda** [comment]
Yes, there is a problem with Unicode strings in dropdowns. 

I will submit a PR.

More info on the isseu with `btoa()` function:
https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem
