### ISSUE TITLE
PHP 8 / dokuwiki master does not seem to work

### ISSUE THREAD

**Issue by rotdrop** [cosmocode/dokuwiki-plugin-prosemirror#140]
A bit naively I tried to use DokuWiki + Prosemirror on a PHP 8 only installation which ATM does not work; DokuWiki seems to run fine, but Prosemirror still uses the Doku_Form class, in particular the HTML_EDITFORM_OUTPUT event is  no longer generated as seemingly the DokuWIki editor already uses the new form class.

**Comment by annda** [comment]
Fixed in a5c9806
