### ISSUE TITLE
HTML pre tag conversion not respecting whitespace

### ISSUE THREAD

**Issue by WebFreak001** [cosmocode/dokuwiki-plugin-prosemirror#143]
when given the following wiki content:

```
<html><pre class="code">
foo

bar() {
    cool()
}
</pre></html>
```

![grafik](https://user-images.githubusercontent.com/2035977/127124225-5e5fda92-22a8-4839-ba3c-fb0f98d15606.png)

switching to the prosemirror editor and back causes the content to look like this:

```
<html><pre class="code"> foo  bar() {     cool() } </pre></html>
```

![grafik](https://user-images.githubusercontent.com/2035977/127124144-8df132d8-7cab-46af-b8ff-65846d23ac02.png)

It's possible that any tag or class may have set white-space to pre by CSS, so if possible the whitespace should be preserved everywhere in `<html>` blocks.

Note: there is a reason why my actual content is in a HTML block, so using a code block wouldn't work in this context.

**Comment by annda** [comment]
If you want to preserve the HTML block with newlines intact, use `<HTML>` instead of `<html>`.
