### ISSUE TITLE
Changes are lost when switching editors with unsaved content

### ISSUE THREAD

**Issue by rotdrop** [cosmocode/dokuwiki-plugin-prosemirror#165]
More precisely:
- switch Wiki-editor -> WYSIWYG-editor: changed content is kept
- switch WYSIWYG-editor -> Wiki-editor: changed content is lost

This is with the current master of both Dokuwiki as the prosemirror plugin.

For me it would be acceptable to just disable the switch-button when the content is "dirty".

**Comment by Klap-in** [comment]
Could you reproduce this behavior on other pages of your wiki?
Or on this test wiki? https://wysiwyg.wiki.cosmocode.de/doku.php?id=en:playground:start

**Comment by rotdrop** [comment]
Ok, the

**Comment by rotdrop** [comment]
Ok, reopening. Regardless of the embedding iframe one problem is that the switch-WYSIWYG button submits the form, as its type is not set to "button", from MDN:
> If your buttons are not for submitting form data to a server, be sure to set their type attribute to button. Otherwise they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document.

The rest probably is some kind of a race condition. Is your playground-Wiki running on the master branch of DokuWiki? I would suggest to add a `return false;` to the `toggleEditor()` handler, or create the toggle-button with a `type="button"` attribute.

**Comment by annda** [comment]
Fixed. Thank you @rotdrop and @TZanke for debugging this issue.
