### ISSUE TITLE
GIF smileys are gone + other smiley menu problems.

### ISSUE THREAD

**Issue by rotdrop** [cosmocode/dokuwiki-plugin-prosemirror#167]
The old smiley-gifs are gone:

https://github.com/splitbrain/dokuwiki/commit/b09504a9ba668bc5e29701fd7c786d5757822b7a

Also, the smiley menu show one long column of smiley instead of two short rows as the Wiki-editor does.

**Comment by rotdrop** [comment]
Could be closed with #168

**Comment by annda** [comment]
Smiley icons have been fixed in d7a145c
