### ISSUE TITLE
Restrict Editor Size

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-prosemirror#26]
Currently the menu scrolls out of view for long pages. It would make sense to restrict the editor window in size (we sure reuse the preference cookie for the size and also use the size control buttons)

**Comment by splitbrain** [comment]
We need to reimplement the size controls and make use of the preference cookie settings.

**Comment by micgro42** [comment]
Editor full size - menu bar sticky(js)
