### ISSUE TITLE
Add input rules

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-prosemirror#63]
This could mean `> ` at the beginning of a paragraph to start a blockquote or `[[` to insert a link.

Examples: https://github.com/ProseMirror/prosemirror-example-setup/blob/master/src/inputrules.js
Documentation: https://prosemirror.net/docs/ref/#inputrules

#### Further Ideas:

- Input rule for indenting a list -- or would that be a key-bind?
- hrule == `----` ?
- input rules for smileys?

**Comment by splitbrain** [comment]
@annda Let's start with implementing smileys.

**Comment by splitbrain** [comment]
Input rules for smileys have been added. When additional rules would be desirable, individual tickets should be opened.
