### ISSUE TITLE
Problem with ~~Makro's~~ on top

### ISSUE THREAD

**Issue by Marcao8** [cosmocode/dokuwiki-plugin-prosemirror#70]
while using the Prosemirror editor, makros become alternated after saving the page(added at the end of the page?). 
This leads to an error, while using makros of plugins, which have to stay on top of the page.
When i add the `~~IREADIT~~` makro of the plugin: https://www.dokuwiki.org/plugin:ireadit to a page and save it once, everything works fine. But when the page is reedited, a new makro code paragraph is added every time. 
It looks like this: https://i.imgur.com/31FfpmC.jpg   and renders the makro useless. Is there any workaround for it? (except using another editor?)
Thank you anyways for this neat editor.

**Comment by annda** [comment]
Prosemirror currently does not support third-party macros, but it shouldn't break them. What you describe looks like a problem with ireadit plugin and should be fixed as soon as https://github.com/gkrid/dokuwiki-plugin-ireadit/pull/14 is merged.

You might want to toggle the traditional editor and check that the macro syntax is still ok.

**Comment by Marcao8** [comment]
Thank you, funny that such a tiny change could make the difference. Have to try it when I’m back at the system.
