### ISSUE TITLE
Displaying plugin codes

### ISSUE THREAD

**Issue by teatall** [cosmocode/dokuwiki-plugin-prosemirror#76]
How could I ask it to display anything wrapped in "<>" as inline plugin? I think this might solve a lot of problems in terms of compatibility with many plugins.

For example:
`<alert info>Some text and [[link]].<alert>`

Could you make the editor to display "`<alert info>`" and "`</alert>`" as inline plugins?

**Comment by splitbrain** [comment]
We cannot simply assume something in ``<>`` is plugin code. Plugin handling needs improvement, eg. by implementing #47 but in general I'm still unsure what the best approach is. I'm closing this issue as it's too unspecific to be actionable.
