### ISSUE TITLE
compatibility with codemirror plugin

### ISSUE THREAD

**Issue by nelbs** [cosmocode/dokuwiki-plugin-prosemirror#81]
There seems to be an compatibility issue regarding the [CodeMirror Plugin](https://www.dokuwiki.org/plugin:codemirror) which Enhances DokuWiki's Editor with syntax highlighting.

Both the dokuwiki editor and the WYSIWYG window are presented at the same time; see this screenshot. I dont now if this is a bug or just normal behaviour but Is there something I can do about is?

![Capture](https://user-images.githubusercontent.com/6464671/63015691-f3b87c00-be91-11e9-8901-8e57e9fcd0ef.PNG)

**Comment by annda** [comment]
It is "normal" or expected behavior, because CodeMirror does conflict with other editors, as stated on its DokuWiki page. Just uninstall or deactivate the plugins you are not using.
