### ISSUE TITLE
Make background image (diagonal stripes) lighter or disable it

### ISSUE THREAD

**Issue by psy-q** [cosmocode/dokuwiki-plugin-prosemirror#88]
Our users find the background image very distracting while writing, the diagonal lines are too dark and interfere with reading lines of text. This could of course be because of varying contrast and gamma settings throughout a range of displays.

Could there perhaps be an option to switch this image off or change it? So far, I simply replaced the CSS with a plain light grey background in my own copy.

**Comment by MrReSc** [comment]
You can insert your CSS into `conf/userstyle.css` and it will survive updates...

`.ProseMirror{
    background: none;
}`

**Comment by psy-q** [comment]
Yes, although I think that doesn't take for animals in a farm (or you have to do it once per animal) :(  I've just hacked it into the main `.less` file now and I'm happy to hack it again when it changes. But it might be cool to have an actual option somehow.

**Comment by splitbrain** [comment]
I guess we need to find a less obtrusive way to signal that the text editable. Suggestions welcome.

**Comment by Juergen-aus-Koeln** [comment]
I would prefer a background color like #FBF2EF as very light red. In this way everyone recognizes that its NOT the normal screen mode.

**Comment by psy-q** [comment]
It might not be discernible for people with color blindness if it's a light shade of red or green. There are vision simulators one could use to test with like https://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by astroHaoPeng** [comment]
Would be better if there is a switch or option provided. Thanks.

**Comment by kontu** [comment]
At a minimum an option to just disable it would be preferred; or let users decide the color.
As it is, it makes it completely unusable with our wiki unless we disable it via userstyles
https://i.imgur.com/wSgxi2k.png

**Comment by solarkraft** [comment]
> I guess we need to find a less obtrusive way to signal that the text editable. Suggestions welcome.

While the user should be reminded they are in edit mode, it's not too crazy of them the expect, then, that the text is visually editable (this is rather the default). The toolbar at the top is a good hint. 

A couple of things can be done to further the user of the editability of the content:

- A border around the text field
- Save/Preview/Cancel buttons at the top (more prominent)
- A textual reminder

Here's a quick mockup of what it could look like: 

<img width="793" alt="Screen Shot 2021-08-20 at 02 53 49" src="https://user-images.githubusercontent.com/1337470/130162135-df64b92e-9b4c-4e2a-8ea5-47c308f47343.png">

**Comment by solarkraft** [comment]
Personally I'm toying with the idea of barely keeping edit and view modes very similar to each other. I like the idea, since it has the potential to reduce friction, which can motivate people to contribute. 

https://user-images.githubusercontent.com/1337470/130210409-822ffbdf-bd27-4253-8259-b3eb9a8a21bd.mov

**Comment by solarkraft** [comment]
This has landed in #147, thus this issue can probably be closed.

**Comment by annda** [comment]
The look has been changed in version 2021-11-11
