### ISSUE TITLE
Font Color Option

### ISSUE THREAD

**Issue by tb72** [cosmocode/dokuwiki-plugin-prosemirror#89]
Maybe I have overseen this, but I can't find a font color option in this nice plugin. I think this is a basic feature.

Thanks,
tb72

**Comment by Klap-in** [comment]
It is a feature that is included in e.g. the wrap plugin.
Please consider that the roadmap is still on going:
https://wysiwyg.wiki.cosmocode.de/doku.php?id=en:roadmap

**Comment by splitbrain** [comment]
DokuWiki does not support font colors by default. This would need to be implemented in a plugin as Klap-In suggested.
