### ISSUE TITLE
Add imgpaste or other paste image from clipboard plugin

### ISSUE THREAD

**Issue by xroot1337** [cosmocode/dokuwiki-plugin-prosemirror#94]
Really great plugin! It's already a must have, I really appreciate the approach compared to ckgedit ! The downside for us is the loss of paste image from clipboard (we're using https://www.dokuwiki.org/plugin:imgpaste), is there a chance to have imgpaste or similar in the roadmap ? Thanks again for your work!

**Comment by pv451** [comment]
> 
> 
> Really great plugin! It's already a must have, I really appreciate the approach compared to ckgedit ! The downside for us is the loss of paste image from clipboard (we're using https://www.dokuwiki.org/plugin:imgpaste), is there a chance to have imgpaste or similar in the roadmap ? Thanks again for your work!

It can be achived from another side, small patch to imgpaste allows you to insert images to prosemirror editor. Made a pull request for this, meanwhile you can patch your instance.

But of course having integrated feature would be great.

**Comment by xroot1337** [comment]
It works great! Thanks for your patch!

**Comment by mschlenstedt** [comment]
Yes, can confirm. Works great!

**Comment by Kblasz** [comment]
> > Really great plugin! It's already a must have, I really appreciate the approach compared to ckgedit ! The downside for us is the loss of paste image from clipboard (we're using https://www.dokuwiki.org/plugin:imgpaste), is there a chance to have imgpaste or similar in the roadmap ? Thanks again for your work!
> 
> It can be achived from another side, small patch to imgpaste allows you to insert images to prosemirror editor. Made a pull request for this, meanwhile you can patch your instance.
> 
> But of course having integrated feature would be great.

I don't think this works anymore. I copied your git version and pasted it into the plugins folder. when I copy and paste an image I get a little green popup in the corner "upload successful" but the image does not appear. I have to then fine the image in the usual image manager window and attach it...which I assume is not how its meant to behave. The syntax editor though works just fine with imgpaste.

**Comment by Kblasz** [comment]
This fork looks to be working great for me. 
https://github.com/Vincent31Fr/dokuwiki-plugin-imgpaste

**Comment by pv451** [comment]
> > > Really great plugin! It's already a must have, I really appreciate the approach compared to ckgedit ! The downside for us is the loss of paste image from clipboard (we're using https://www.dokuwiki.org/plugin:imgpaste), is there a chance to have imgpaste or similar in the roadmap ? Thanks again for your work!
> > 
> > 
> > It can be achived from another side, small patch to imgpaste allows you to insert images to prosemirror editor. Made a pull request for this, meanwhile you can patch your instance.
> > But of course having integrated feature would be great.
> 
> I don't think this works anymore. I copied your git version and pasted it into the plugins folder. when I copy and paste an image I get a little green popup in the corner "upload successful" but the image does not appear. I have to then fine the image in the usual image manager window and attach it...which I assume is not how its meant to behave. The syntax editor though works just fine with imgpaste.

Still works for me. It was slightly refactored last year, but still was not good enough to be merged with master.
Code for this feature in repository you refer is quite same. Thanks for your feedback anyway.

**Comment by annda** [comment]
The latest version of imgpaste works with ProseMirror. As a bonus, it works with larger clipboard content with mixed text and multiple images: https://www.dokuwiki.org/plugin:imgpaste#prosemirror_support
