### ISSUE TITLE
test documentation

### ISSUE THREAD

**Issue by th-we** [cosmocode/dokuwiki-plugin-prosemirror#99]
I'd love to contribute and I'd like to know how to run the PHP tests.  The [README](https://github.com/cosmocode/dokuwiki-plugin-prosemirror/blob/master/README.md#testing) says:

> The rendering and parsing tests are run as usual DokuWiki tests.

[devel:unittesting](https://www.dokuwiki.org/devel:unittesting) says I should do this:

    $ cd _test/
    $ phpunit

However, that only prints the Usage info of phpunit.  So I tried this:

    $ phpunit _test/renderer.test.php 
    PHP Fatal error:  Class 'DokuWikiTest' not found in /home/tom/devel/dokuwiki-plugin-prosemirror/_test/renderer.test.php on line 9

Could you update the README to give more specific instructions?  Adding the PHP tests to `npm test` would also be useful.

**Comment by th-we** [comment]
O.K., I'm guilty of not RTFM completely at [devel:unittesting](https://www.dokuwiki.org/devel:unittesting). So, what I did is the following:

```
$ clone git@github.com:splitbrain/dokuwiki.git
$ clone git@github.com:cosmocode/dokuwiki-plugin-prosemirror.git
$ ln -s $(readlink -e dokuwiki-plugin-prosemirror) dokuwiki/lib/plugins/prosemirror
$ cd dokuwiki/_test
$ phpunit ../lib/plugins/prosemirror/_test/general.test.php 
$ phpunit ../lib/plugins/prosemirror/_test/jsonParser.test.php 
$ phpunit ../lib/plugins/prosemirror/_test/nodestack.test.php 
$ phpunit ../lib/plugins/prosemirror/_test/node.test.php 
$ phpunit ../lib/plugins/prosemirror/_test/renderer.test.php 
```

(`renderer.test.php` givers me 9 errors and 1 failure – I assume that's expected as the plugin still needs work.)

Should these steps be documented in the README?

**Comment by th-we** [comment]
The one failure is due to the [wrap plugin](https://www.dokuwiki.org/plugin:wrap) not being installed. Would also help to document that.

**Comment by annda** [comment]
Take a look at [devel:unittesting#](https://www.dokuwiki.org/devel:unittesting#grouped_tests) for the recommended way to test plugins. That is what the first sentence you quoted refers to. 

DokuWiki's `_test/` directory, where the tests are run from, contains a PHPUnit configuration file `phpunit.xml`. Because there is no configuration in the plugin's test directory, simply running `phpunit` without arguments from there does not execute any tests.

**Comment by annda** [comment]
> The one failure is due to the [wrap plugin](https://www.dokuwiki.org/plugin:wrap) not being installed. Would also help to document that.

You are right, that information was missing from the documentation, I just added it.
